name: Playwright tests
run-name: Running playwright tests
on:
  pull_request:
    types: [opened, reopened]
    branches: [main, master]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.12"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Install Playwright
        run: npm i -D @playwright/test --legacy-peer-deps
      - name: Install PLaywright Browsers
        run: npx playwright install
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
